name:                jsonf
version:             0.1.0.0
github:              "ChrisPenner/jsonf"
license:             BSD3
author:              "Chris Penner"
maintainer:          "christopher.penner@gmail.com"
copyright:           "2018 Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/jsonf#readme>

dependencies:
- base >= 4.7 && < 5
- recursion-schemes
- containers
- aeson
- free
- text
- unordered-containers
- vector
- deriving-compat

library:
  source-dirs: src
